import js from '@eslint/js';
import importX from 'eslint-plugin-import-x';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import ts from 'typescript-eslint';
import noUnqualifiedKyselyColumns from './eslint-rules/no-unqualified-kysely-columns.js';
import svelteConfig from './apps/web/svelte.config.js';

// One flat config for the whole workspace, deliberately not one per package.
// It is a single eslint process rather than three, and — more to the point —
// it is the only place the cross-package import boundaries below can live.
export default ts.config(
  {
    ignores: [
      '**/dist/',
      '**/dev-dist/',
      '**/coverage/',
      '**/node_modules/',
      '**/*.generated.ts',
      'scripts/tmp-*',
      'apps/*/scripts/tmp-*',
      'infra/',
    ],
  },
  js.configs.recommended,
  ...ts.configs.recommended,

  {
    languageOptions: {
      parserOptions: { tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': 'off',
    },
  },

  // --- Cross-package boundaries -------------------------------------------
  // Each of these is a build-order or correctness invariant that would
  // otherwise be a paragraph in CLAUDE.md someone has to remember. Making them
  // lint errors puts the failure at the import site.

  {
    // packages/shared is generated FROM this app, so an import of the generated
    // half here is a cycle: a broken spec would make the API un-typecheckable,
    // which makes it un-dumpable, which is what produces the spec. The
    // hand-written half of shared is fine to import.
    files: ['apps/api/**/*.ts'],
    plugins: { local: { rules: { 'no-unqualified-kysely-columns': noUnqualifiedKyselyColumns } } },
    rules: {
      'local/no-unqualified-kysely-columns': 'error',
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@three-peaks/shared/api', '@three-peaks/shared/realtime'],
              message: 'apps/api must never import the client generated from it.',
            },
          ],
        },
      ],
    },
  },

  {
    // shared is loaded by a Node server, a browser bundle and jsdom. Anything
    // platform-specific breaks one of the three, at runtime, in whichever
    // consumer nobody happened to be looking at.
    files: ['packages/shared/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['node:*', 'hono', 'hono/*', 'kysely', 'kysely/*', 'svelte', 'svelte/*'],
              message: 'packages/shared must stay platform-neutral.',
            },
          ],
        },
      ],
    },
  },

  {
    // Migrations are frozen history. They load as loose .ts at runtime, outside
    // the bundle, and a shared constant one of them reaches for will be renamed
    // six months from now — silently changing what an already-applied migration
    // means on a fresh database.
    files: ['apps/api/src/db/migrations/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@three-peaks/*', '../**', './**'],
              message: 'A migration may import only kysely.',
            },
          ],
        },
      ],
    },
  },

  {
    // IDs are client-generated by newId(). The restriction lives here so the
    // point is made where the import would go.
    files: ['apps/web/**/*.{ts,svelte}'],
    languageOptions: { globals: { ...globals.browser } },
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'uuid',
              message:
                'IDs are client-generated by newId() in src/lib/ids.ts. Do not install uuid.',
            },
          ],
        },
      ],
    },
  },

  // --- Svelte --------------------------------------------------------------
  ...svelte.configs.recommended,
  {
    files: ['**/*.svelte.ts', '**/*.svelte.js'],
    languageOptions: { parser: ts.parser },
  },
  {
    files: ['**/*.svelte'],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
        extraFileExtensions: ['.svelte'],
        // eslint-plugin-svelte resolves svelte.config.js relative to the
        // process cwd, and the cwd is the repo root now rather than apps/web.
        // Left out, it degrades silently to non-runes parsing.
        svelteConfig,
      },
    },
  },

  // --- Import order --------------------------------------------------------
  // Groups only, deliberately not alphabetised. This rule is autofixable and
  // the post-commit hook runs the fixer, so there is no placement judgement to
  // make and no house style to infer from whichever file you happen to open.
  {
    files: ['**/*.{ts,svelte}'],
    plugins: { 'import-x': importX },
    rules: {
      'import-x/order': [
        'error',
        {
          groups: [['builtin', 'external'], 'internal', ['parent', 'sibling', 'index']],
          'newlines-between': 'never',
          warnOnUnassignedImports: true,
        },
      ],
    },
  },
  {
    files: ['apps/web/src/**/*.test.ts'],
    plugins: { 'import-x': importX },
    rules: {
      'import-x/order': [
        'error',
        {
          groups: [['builtin', 'external'], 'internal', ['parent', 'sibling', 'index']],
          'newlines-between': 'never',
          warnOnUnassignedImports: true,
          pathGroups: [
            {
              pattern: '{.,..}/**/testUtils.ts',
              group: 'builtin',
              position: 'before',
            },
          ],
          pathGroupsExcludedImportTypes: [],
        },
      ],
    },
  },

  {
    files: ['**/*.mjs', 'scripts/**/*.mjs'],
    languageOptions: { globals: globals.node },
    rules: { 'no-undef': 'off' },
  }
);
