// Regenerates src/db/types.generated.ts.
//
// It migrates a SCRATCH database from src/db/migrations, introspects that, and
// drops it. It never reads the database you develop against -- introspecting
// that is how a column left behind by an abandoned branch gets committed
// looking exactly like a real one. The scratch name carries this checkout, so
// parallel worktrees can regenerate at once.
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { basename } from 'node:path';
import pg from 'pg';
import { env } from '../src/config/env.ts';
import { checkoutRoot } from '../tests/setup/testDatabaseName.ts';

const OUT_FILE = 'src/db/types.generated.ts';

const GENERATOR_BANNER = `/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */
`;

const HEADER = `// AUTO-GENERATED. DO NOT EDIT.
// Regenerate with: pnpm --filter @three-peaks/api run kysely-codegen
//
// The generator migrates a scratch database from src/db/migrations, introspects
// that, and drops it. It never reads the database you develop against, so a
// column left behind by an abandoned branch cannot land in a commit looking
// exactly like a real one.

`;

const hash = createHash('sha256').update(checkoutRoot).digest('hex').slice(0, 8);
const scratch = `three_peaks_hub_codegen_${basename(checkoutRoot)
  .replace(/[^a-z0-9]+/gi, '_')
  .toLowerCase()}_${hash}`.slice(0, 63);

function maintenance() {
  return new pg.Client({
    host: env.db.hostname,
    port: env.db.port,
    user: env.db.user,
    password: env.db.password,
    database: env.db.maintenanceDatabase,
  });
}

const setup = maintenance();
await setup.connect();
await setup.query(`drop database if exists "${scratch}"`);
await setup.query(`create database "${scratch}"`);
await setup.end();

const url = `postgres://${env.db.user}:${encodeURIComponent(env.db.password)}@${env.db.hostname}:${env.db.port}/${scratch}`;

try {
  const migrated = spawnSync('node', ['--import', 'tsx', 'src/db/migrate-cli.ts'], {
    stdio: 'inherit',
    env: { ...process.env, DB_DATABASE: scratch },
  });
  if (migrated.status !== 0) throw new Error('migrations failed against the scratch database');

  const generated = spawnSync(
    'pnpm',
    [
      'exec',
      'kysely-codegen',
      '--url',
      url,
      '--dialect',
      'postgres',
      '--out-file',
      OUT_FILE,
      // Renamed from --singular in kysely-codegen 0.20; the old spelling is a
      // hard error rather than a warning.
      '--singularize',
      'false',
    ],
    { stdio: 'inherit' }
  );
  if (generated.status !== 0) throw new Error('kysely-codegen failed');

  // kysely-codegen writes its own two-line banner and nothing else, so the
  // header belongs to this script -- left to the generator it is silently
  // dropped on the next run.
  const body = readFileSync(OUT_FILE, 'utf8').replace(GENERATOR_BANNER, '');
  writeFileSync(OUT_FILE, HEADER + body.trimStart());

  spawnSync('pnpm', ['exec', 'prettier', '--write', '--log-level', 'warn', OUT_FILE], {
    stdio: 'inherit',
  });
} finally {
  const teardown = maintenance();
  await teardown.connect();
  await teardown.query(`drop database if exists "${scratch}"`);
  await teardown.end();
}

console.log(`wrote ${OUT_FILE}`);
